## Metropolitan and Micropolitan Incorporated Areas Only

2020 Census Race Statistics

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
metro_micro_data = pd.read_csv('../Fatal-Police-Shootings-WaPo/data/UnprocessedCensusData/Metro-Micro-R-Census2020.csv')

In [49]:
mm_df = metro_micro_data.copy()

There are 940 cities/towns included in the "Metropolitan" and "Micropolitan" Areas of the 2020 Census

In [50]:
mm_df.set_index(keys=mm_df['Label (Grouping)'], inplace=True)

In [51]:
mm_df = mm_df.transpose()

In [52]:
mm_df = mm_df.drop('Label (Grouping)')

In [53]:
mm_df

Label (Grouping),Total:,Hispanic or Latino,Not Hispanic or Latino:,Population of one race:,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,...,American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Population of five races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race,White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Population of six races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
"Aberdeen, SD Micro Area","42,287","1,720","40,567","39,254","36,484",547,"1,142",941,44,96,...,0,0,0,0,0,0,0,0,0,0
"Aberdeen, WA Micro Area","75,636","7,834","67,802","63,097","57,068",972,"3,495","1,024",127,411,...,0,5,0,0,0,0,0,5,3,3
"Abilene, TX Metro Area","176,579","41,566","135,013","127,862","110,356","13,076",721,"2,978",172,559,...,0,3,2,1,0,0,0,0,0,0
"Ada, OK Micro Area","38,065","2,208","35,857","30,889","22,703",861,"6,842",372,13,98,...,0,0,0,0,0,0,0,0,0,0
"Adrian, MI Micro Area","99,423","8,494","90,929","86,688","83,126","2,437",342,476,8,299,...,0,2,0,0,0,0,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area","181,208","55,088","126,120","114,935","83,116","4,605","1,896","23,597",651,"1,070",...,0,18,2,5,3,8,0,0,0,0
"Yuma, AZ Metro Area","203,881","130,003","73,878","69,653","61,123","3,484","1,888","2,321",215,622,...,0,22,4,16,0,2,0,0,0,0
"Zanesville, OH Micro Area","86,410","1,055","85,355","80,840","76,947","2,985",138,384,8,378,...,0,1,1,0,0,0,0,0,0,0
"Zapata, TX Micro Area","13,889","12,999",890,844,796,9,7,16,0,16,...,0,0,0,0,0,0,0,0,0,0
United States,"331,449,281","62,080,044","269,369,237","255,820,254","191,697,647","39,940,338","2,251,699","19,618,719","622,018","1,689,833",...,150,"9,103","5,247","2,604",348,433,244,227,"1,004","1,004"

In [54]:
cols = mm_df.columns
mm_df[cols] = mm_df[cols].replace({',':''}, regex=True)

In [55]:
mm_df = mm_df.astype(int)

In [56]:
total_values = mm_df['Total:'].values

In [57]:
indices = mm_df.index
percent_df = mm_df.copy()
for column in mm_df:
    column_series = mm_df[column]
    percent_df[column] = (column_series/mm_df['Total:']) * 100

percent_df will copied for fractional manipulation

In [58]:
computed_df = mm_df.copy()

In [59]:
columns = computed_df.columns

In [60]:
columns

Index(['Total:', 'Hispanic or Latino', 'Not Hispanic or Latino:',
       'Population of one race:', 'White alone',
       'Black or African American alone',
       'American Indian and Alaska Native alone', 'Asian alone',
       'Native Hawaiian and Other Pacific Islander alone',
       'Some Other Race alone', 'Population of two or more races:',
       'Population of two races:', 'White; Black or African American',
       'White; American Indian and Alaska Native', 'White; Asian',
       'White; Native Hawaiian and Other Pacific Islander',
       'White; Some Other Race',
       'Black or African American; American Indian and Alaska Native',
       'Black or African American; Asian',
       ' Black or African American; Native Hawaiian and Other Pacific Islander',
       'Black or African American; Some Other Race',
       'American Indian and Alaska Native; Asian',
       'American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander',
       'American Indian and Alaska Native; Some Other Race',
       'Asian; Native Hawaiian and Other Pacific Islander',
       'Asian; Some Other Race',
       'Native Hawaiian and Other Pacific Islander; Some Other Race',
       '            Population of three races:',
       '                White; Black or African American; American Indian and Alaska Native',
       '                White; Black or African American; Asian',
       '                White; Black or African American; Native Hawaiian and Other Pacific Islander',
       '                White; Black or African American; Some Other Race',
       '                White; American Indian and Alaska Native; Asian',
       '                White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander',
       '                White; American Indian and Alaska Native; Some Other Race',
       '                White; Asian; Native Hawaiian and Other Pacific Islander',
       '                White; Asian; Some Other Race',
       '                White; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                Black or African American; American Indian and Alaska Native; Asian',
       '                Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander',
       '                Black or African American; American Indian and Alaska Native; Some Other Race',
       '                Black or African American; Asian; Native Hawaiian and Other Pacific Islander',
       '                Black or African American; Asian; Some Other Race',
       '                Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander',
       '                American Indian and Alaska Native; Asian; Some Other Race',
       '                American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '            Population of four races:',
       '                White; Black or African American; American Indian and Alaska Native; Asian',
       '                White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander',
       '                White; Black or African American; American Indian and Alaska Native; Some Other Race',
       '                White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander',
       '                White; Black or African American; Asian; Some Other Race',
       '                White; Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander',
       '                White; American Indian and Alaska Native; Asian; Some Other Race',
       '                White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                White; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander',
       '                Black or African American; American Indian and Alaska Native; Asian; Some Other Race',
       '                Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '            Population of five races:',
       '                White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander',
       '                White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race',
       '                White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '                Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race',
       '            Population of six races:',
       '                White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race'],
      dtype='object', name='Label (Grouping)')

**Compute Fractions**

In [61]:
# 15 combos of 2
computed_df.iloc[:,10:28]

Label (Grouping),Population of two or more races:,Population of two races:,White; Black or African American,White; American Indian and Alaska Native,White; Asian,White; Native Hawaiian and Other Pacific Islander,White; Some Other Race,Black or African American; American Indian and Alaska Native,Black or African American; Asian,Black or African American; Native Hawaiian and Other Pacific Islander,Black or African American; Some Other Race,American Indian and Alaska Native; Asian,American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander,American Indian and Alaska Native; Some Other Race,Asian; Native Hawaiian and Other Pacific Islander,Asian; Some Other Race,Native Hawaiian and Other Pacific Islander; Some Other Race,Population of three races:
"Aberdeen, SD Micro Area",1313,1264,221,677,130,10,186,23,6,0,3,5,1,0,1,1,0,48
"Aberdeen, WA Micro Area",4705,4452,439,2208,629,106,802,24,18,0,24,55,14,0,132,0,1,237
"Abilene, TX Metro Area",7151,6725,1764,2695,851,58,982,100,84,10,90,7,3,15,59,3,4,396
"Ada, OK Micro Area",4968,4607,337,3573,111,10,199,343,6,2,6,13,3,0,1,3,0,356
"Adrian, MI Micro Area",4241,4106,962,1848,395,14,843,16,8,0,17,1,0,0,0,2,0,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",11185,10269,1443,4210,2067,248,1582,109,164,23,53,90,19,13,147,95,6,808
"Yuma, AZ Metro Area",4225,3967,592,1241,680,108,1079,76,58,21,12,11,10,13,54,6,6,212
"Zanesville, OH Micro Area",4515,4158,1897,1368,183,18,568,76,0,0,44,1,0,0,3,0,0,353
"Zapata, TX Micro Area",46,40,4,14,6,0,11,1,0,1,0,0,0,0,3,0,0,5
United States,13548983,12637189,2781839,3539935,2521775,198640,2284608,344276,224198,40790,354439,37784,8067,14766,197918,76457,11697,830158

In [62]:
# 20 combos of 3
computed_df.iloc[:,28:48]

Label (Grouping),White; Black or African American; American Indian and Alaska Native,White; Black or African American; Asian,White; Black or African American; Native Hawaiian and Other Pacific Islander,White; Black or African American; Some Other Race,White; American Indian and Alaska Native; Asian,White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander,White; American Indian and Alaska Native; Some Other Race,White; Asian; Native Hawaiian and Other Pacific Islander,White; Asian; Some Other Race,White; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; American Indian and Alaska Native; Asian,Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander,Black or African American; American Indian and Alaska Native; Some Other Race,Black or African American; Asian; Native Hawaiian and Other Pacific Islander,Black or African American; Asian; Some Other Race,Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race,American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,American Indian and Alaska Native; Asian; Some Other Race,American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
"Aberdeen, SD Micro Area",22,1,0,3,15,0,0,2,1,0,0,0,4,0,0,0,0,0,0,0
"Aberdeen, WA Micro Area",70,15,4,12,58,17,2,44,7,0,0,0,0,2,0,2,2,0,0,2
"Abilene, TX Metro Area",139,82,12,31,26,17,17,23,8,0,0,0,7,20,12,0,1,0,0,1
"Ada, OK Micro Area",269,5,0,12,52,2,10,4,0,0,0,0,0,2,0,0,0,0,0,0
"Adrian, MI Micro Area",59,19,6,9,7,0,9,8,0,0,1,0,1,0,0,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",296,112,22,29,121,28,11,130,19,4,6,0,9,5,5,0,0,0,0,11
"Yuma, AZ Metro Area",69,21,6,14,29,0,10,54,3,0,0,1,0,1,0,0,4,0,0,0
"Zanesville, OH Micro Area",295,4,9,15,11,0,4,7,3,0,0,0,0,0,0,0,5,0,0,0
"Zapata, TX Micro Area",0,0,0,0,0,0,3,0,0,0,0,2,0,0,0,0,0,0,0,0
United States,303459,104194,14293,65741,72235,12094,17723,175677,19468,2224,9824,2438,7495,9342,7177,1365,2373,773,180,2083

In [63]:
# 15 combos of 4
computed_df.iloc[:,49:64]

Label (Grouping),White; Black or African American; American Indian and Alaska Native; Asian,White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander,White; Black or African American; American Indian and Alaska Native; Some Other Race,White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander,White; Black or African American; Asian; Some Other Race,White; Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race,White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,White; American Indian and Alaska Native; Asian; Some Other Race,White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,White; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,Black or African American; American Indian and Alaska Native; Asian; Some Other Race,Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
"Aberdeen, SD Micro Area",0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
"Aberdeen, WA Micro Area",2,0,6,0,0,0,0,0,0,0,0,0,0,0,0
"Abilene, TX Metro Area",2,4,10,5,0,0,0,1,0,4,0,1,0,0,0
"Ada, OK Micro Area",3,1,0,0,1,0,0,0,0,0,0,0,0,0,0
"Adrian, MI Micro Area",6,2,3,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",30,13,15,7,1,0,10,9,0,2,2,0,1,0,0
"Yuma, AZ Metro Area",17,3,0,1,0,0,0,0,0,1,0,0,0,2,0
"Zanesville, OH Micro Area",1,0,0,2,0,0,0,0,0,0,0,0,0,0,0
"Zapata, TX Micro Area",0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
United States,24056,3933,13875,7242,4627,587,11703,1020,194,1617,1046,618,177,684,150

In [64]:
# 6 combos of 5
computed_df.iloc[:,64:]

Label (Grouping),Population of five races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race,White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Population of six races:,White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
"Aberdeen, SD Micro Area",0,0,0,0,0,0,0,0,0
"Aberdeen, WA Micro Area",5,0,0,0,0,0,5,3,3
"Abilene, TX Metro Area",3,2,1,0,0,0,0,0,0
"Ada, OK Micro Area",0,0,0,0,0,0,0,0,0
"Adrian, MI Micro Area",2,0,0,0,0,2,0,0,0
...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",18,2,5,3,8,0,0,0,0
"Yuma, AZ Metro Area",22,4,16,0,2,0,0,0,0
"Zanesville, OH Micro Area",1,1,0,0,0,0,0,0,0
"Zapata, TX Micro Area",0,0,0,0,0,0,0,0,0
United States,9103,5247,2604,348,433,244,227,1004,1004

In [65]:
# 1 combo of 6
computed_df.iloc[:,72:73]

Label (Grouping)                           White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
Aberdeen, SD Micro Area                                                    0
Aberdeen, WA Micro Area                                                    3
Abilene, TX Metro Area                                                     0
Ada, OK Micro Area                                                         0
Adrian, MI Micro Area                                                      0
...                                                                      ...
Yuba City, CA Metro Area                                                   0
Yuma, AZ Metro Area                                                        0
Zanesville, OH Micro Area                                                  0
Zapata, TX Micro Area                                                      0
United States                                                           1004

[940 rows x 1 columns]

count(';') 1 = 2 races, 2 = 3 races
add 1/(count(;)+1) to each matching 'white' between ';' with regex

In [66]:
# responses: one race alone and "2 or more races:"
one_race_df = computed_df.iloc[:,:11].copy()

In [67]:
full_multiracial_df = computed_df.iloc[:,10:].copy()

In [68]:
full_multiracial_df[['WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC']] = 0

full_multiracial_df has 68 columns including totals i.e. "Population of two races:"

In [69]:
for column in full_multiracial_df.columns:
    # starting count at 1 because 1 ; splits 2 races
    #cat_total = multiracial_df.loc[index][column]
    if ';' in column:
        fraction = 0
        numchar = 1
        count = column.count(';')
        numchar += count
        fraction += 1/numchar
        print(f'column: {column}')
        print(f'number of races: {numchar}')
        print(f'fraction: {fraction}')
        wfracs = 0
        bfracs = 0
        afracs = 0
        aianfracs = 0
        ofracs = 0
        nhpifracs = 0
        if column.count('White') != 0:
            wfrac = fraction * full_multiracial_df[column]
            wfracs += wfrac
        if column.count('Black or African American') != 0:
            bfrac = fraction * full_multiracial_df[column]
            bfracs += bfrac
        if column.count('American Indian and Alaska Native') != 0:
            aianfrac = fraction * full_multiracial_df[column]
            aianfracs += aianfrac
        if column.count('Asian') != 0:
            afrac = fraction * full_multiracial_df[column]
            afracs += afrac
        if column.count('Some Other Race') != 0:
            ofrac = fraction * full_multiracial_df[column]
            ofracs += ofrac
        if column.count('Native Hawaiian and Other Pacific Islander') != 0:
            nhpifrac = fraction * full_multiracial_df[column]
            nhpifracs += nhpifrac
        full_multiracial_df['WFRAC'] += wfracs
        full_multiracial_df['AFRAC'] += afracs
        full_multiracial_df['OFRAC'] += ofracs
        full_multiracial_df['NHPIFRAC'] += nhpifracs
        full_multiracial_df['AIANFRAC'] += aianfracs
        full_multiracial_df['BFRAC'] += bfracs

column: White; Black or African American
number of races: 2
fraction: 0.5
column: White; American Indian and Alaska Native
number of races: 2
fraction: 0.5
column: White; Asian
number of races: 2
fraction: 0.5
column: White; Native Hawaiian and Other Pacific Islander
number of races: 2
fraction: 0.5
column: White; Some Other Race
number of races: 2
fraction: 0.5
column: Black or African American; American Indian and Alaska Native
number of races: 2
fraction: 0.5
column: Black or African American; Asian
number of races: 2
fraction: 0.5
column:  Black or African American; Native Hawaiian and Other Pacific Islander
number of races: 2
fraction: 0.5
column: Black or African American; Some Other Race
number of races: 2
fraction: 0.5
column: American Indian and Alaska Native; Asian
number of races: 2
fraction: 0.5
column: American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander
number of races: 2
fraction: 0.5
column: American Indian and Alaska Native; Some Other Race
number of races: 2
fraction: 0.5
column: Asian; Native Hawaiian and Other Pacific Islander
number of races: 2
fraction: 0.5
column: Asian; Some Other Race
number of races: 2
fraction: 0.5
column: Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 2
fraction: 0.5
column:                 White; Black or African American; American Indian and Alaska Native
number of races: 3
fraction: 0.3333333333333333
column:                 White; Black or African American; Asian
number of races: 3
fraction: 0.3333333333333333
column:                 White; Black or African American; Native Hawaiian and Other Pacific Islander
number of races: 3
fraction: 0.3333333333333333
column:                 White; Black or African American; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 White; American Indian and Alaska Native; Asian
number of races: 3
fraction: 0.3333333333333333
column:                 White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander
number of races: 3
fraction: 0.3333333333333333
column:                 White; American Indian and Alaska Native; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 White; Asian; Native Hawaiian and Other Pacific Islander
number of races: 3
fraction: 0.3333333333333333
column:                 White; Asian; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 White; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 Black or African American; American Indian and Alaska Native; Asian
number of races: 3
fraction: 0.3333333333333333
column:                 Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander
number of races: 3
fraction: 0.3333333333333333
column:                 Black or African American; American Indian and Alaska Native; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 Black or African American; Asian; Native Hawaiian and Other Pacific Islander
number of races: 3
fraction: 0.3333333333333333
column:                 Black or African American; Asian; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander
number of races: 3
fraction: 0.3333333333333333
column:                 American Indian and Alaska Native; Asian; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 3
fraction: 0.3333333333333333
column:                 White; Black or African American; American Indian and Alaska Native; Asian
number of races: 4
fraction: 0.25
column:                 White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander
number of races: 4
fraction: 0.25
column:                 White; Black or African American; American Indian and Alaska Native; Some Other Race
number of races: 4
fraction: 0.25
column:                 White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander
number of races: 4
fraction: 0.25
column:                 White; Black or African American; Asian; Some Other Race
number of races: 4
fraction: 0.25
column:                 White; Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 4
fraction: 0.25
column:                 White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander
number of races: 4
fraction: 0.25
column:                 White; American Indian and Alaska Native; Asian; Some Other Race
number of races: 4
fraction: 0.25
column:                 White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 4
fraction: 0.25
column:                 White; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 4
fraction: 0.25
column:                 Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander
number of races: 4
fraction: 0.25
column:                 Black or African American; American Indian and Alaska Native; Asian; Some Other Race
number of races: 4
fraction: 0.25
column:                 Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 4
fraction: 0.25
column:                 Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 4
fraction: 0.25
column:                 American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 4
fraction: 0.25
column:                 White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander
number of races: 5
fraction: 0.2
column:                 White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race
number of races: 5
fraction: 0.2
column:                 White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 5
fraction: 0.2
column:                 White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 5
fraction: 0.2
column:                 White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 5
fraction: 0.2
column:                 Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 5
fraction: 0.2
column:                 White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
number of races: 6
fraction: 0.16666666666666666

In [70]:
# check the values of a row add up to "Population of two races:" by sum with axis=1

In [71]:
# sum components into a total to check it adds to "Population of two or more races:"
full_multiracial_df['FRACTotal'] = full_multiracial_df[['WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC']].sum(axis=1).round(2)

In [72]:
full_multiracial_df[['Population of two or more races:', 'FRACTotal']]

Label (Grouping)           Population of two or more races:   FRACTotal
Aberdeen, SD Micro Area                                1313      1313.0
Aberdeen, WA Micro Area                                4705      4705.0
Abilene, TX Metro Area                                 7151      7151.0
Ada, OK Micro Area                                     4968      4968.0
Adrian, MI Micro Area                                  4241      4241.0
...                                                     ...         ...
Yuba City, CA Metro Area                              11185     11185.0
Yuma, AZ Metro Area                                    4225      4225.0
Zanesville, OH Micro Area                              4515      4515.0
Zapata, TX Micro Area                                    46        46.0
United States                                      13548983  13548983.0

[940 rows x 2 columns]

In [73]:
full_multiracial_df['diff_test'] = full_multiracial_df['Population of two or more races:'] - full_multiracial_df['FRACTotal']

(full_multiracial_df['diff_test'] > 0).sum()

0

All of the rows where FRACTotal isn't exact are off by exactly 1. This is probably a rounding or math error somewhere when I changed from int to float.

The differences turned out to be fractions of a hundredth. Needed to round float data.

In [74]:
# check the math to see if each column calculated properly and can be added back in
for index in full_multiracial_df.index:
    row = full_multiracial_df.loc[index]
    if row['Population of two or more races:'] == row['FRACTotal']:
        print('y')
    else: print(index)

y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
y

WFRAC, BFRAC, AFRAC, OFRAC, AIANFRAC, NHPIFRAC are all computed to be added to one-race columns

In [75]:
full_multiracial_df[['WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC']] = full_multiracial_df[['WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC']].round(3)

In [76]:
multirace_mapped_fraction_df = full_multiracial_df[['Population of two or more races:', 'WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC', 'FRACTotal']].copy()

In [77]:
multirace_mapped_fraction_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 940 entries, Aberdeen, SD Micro Area to United States
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Population of two or more races:  940 non-null    int64
 1   WFRAC                             940 non-null    float64
 2   BFRAC                             940 non-null    float64
 3   AFRAC                             940 non-null    float64
 4   OFRAC                             940 non-null    float64
 5   AIANFRAC                          940 non-null    float64
 6   NHPIFRAC                          940 non-null    float64
 7   FRACTotal                         940 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 98.4+ KB

In [78]:
df = computed_df.iloc[:,:11].copy().astype(float)

In [79]:
df[['Population of two or more races:', 'WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC','FRACTotal']] = 0

In [80]:
df[['Population of two or more races:', 'WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC','FRACTotal']] = full_multiracial_df[['Population of two or more races:', 'WFRAC', 'BFRAC', 'AFRAC', 'OFRAC', 'AIANFRAC', 'NHPIFRAC', 'FRACTotal']].copy().astype(float).round(3)

In [81]:
df['White Alone and in Combination'] = df[['White alone', 'WFRAC']].sum(axis=1).astype(float).round(3)
df['Black Alone and in Combination'] = df[['Black or African American alone', 'BFRAC']].sum(axis=1).astype(float).round(3)
df['Asian Alone and in Combination'] = df[['Asian alone', 'AFRAC']].sum(axis=1).astype(float).round(3)
df['Other Alone and in Combination'] = df[['Some Other Race alone', 'OFRAC']].sum(axis=1).astype(float).round(3)
df['Native Alone and in Combination'] = df[['American Indian and Alaska Native alone', 'AIANFRAC']].sum(axis=1).astype(float).round(3)
df['NHPI Alone and in Combination'] = df[['Native Hawaiian and Other Pacific Islander alone', 'NHPIFRAC']].sum(axis=1).astype(float).round(3)

In [82]:
multirace_mapped_fraction_df

Label (Grouping),Population of two or more races:,WFRAC,BFRAC,AFRAC,OFRAC,AIANFRAC,NHPIFRAC,FRACTotal
"Aberdeen, SD Micro Area",1313,626.917,136.750,77.833,97.917,366.917,6.667,1313.0
"Aberdeen, WA Micro Area",4705,2170.833,291.000,462.333,424.833,1203.667,152.333,4705.0
"Abilene, TX Metro Area",7151,3300.433,1131.100,563.517,576.533,1484.100,95.317,7151.0
"Ada, OK Micro Area",4968,2234.250,444.250,89.000,111.583,2078.000,10.917,4968.0
"Adrian, MI Micro Area",4241,2073.400,535.917,217.483,439.150,962.233,12.817,4241.0
...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",11185,5057.683,1078.183,1436.083,914.033,2399.500,299.517,11185.0
"Yuma, AZ Metro Area",4225,1928.567,426.983,451.483,571.350,722.167,124.450,4225.0
"Zanesville, OH Micro Area",4515,2133.950,1117.117,104.450,313.333,827.950,18.200,4515.0
"Zapata, TX Micro Area",46,18.750,3.917,4.750,6.500,9.167,2.917,46.0
United States,13548983,5944923.867,2064030.717,1678557.083,1419218.950,2131373.000,310879.383,13548983.0

In [83]:
completed_df = pd.DataFrame()

In [84]:
completed_df[['Total:', 'Hispanic or Latino', 'Not Hispanic or Latino:', 'Population of one race:', 'Population of two or more races:', 'FRACTotal', 'White Alone and in Combination', 'Black Alone and in Combination', 'Asian Alone and in Combination', 'Other Alone and in Combination', 'Native Alone and in Combination', 'NHPI Alone and in Combination']] = df[['Total:', 'Hispanic or Latino', 'Not Hispanic or Latino:', 'Population of one race:', 'Population of two or more races:', 'FRACTotal', 'White Alone and in Combination', 'Black Alone and in Combination', 'Asian Alone and in Combination', 'Other Alone and in Combination', 'Native Alone and in Combination', 'NHPI Alone and in Combination']].copy().astype(float).round(3)

In [85]:
completed_df['Calc Total (Not Latino)'] = completed_df.iloc[:,6:].copy().sum(axis=1).astype(float).round(3)

In [86]:
completed_df

,Total:,Hispanic or Latino,Not Hispanic or Latino:,Population of one race:,Population of two or more races:,FRACTotal,White Alone and in Combination,Black Alone and in Combination,Asian Alone and in Combination,Other Alone and in Combination,Native Alone and in Combination,NHPI Alone and in Combination,Calc Total (Not Latino)
"Aberdeen, SD Micro Area",42287.0,1720.0,40567.0,39254.0,1313.0,1313.0,3.711092e+04,6.837500e+02,1.018833e+03,193.917,1508.917,50.667,4.056700e+04
"Aberdeen, WA Micro Area",75636.0,7834.0,67802.0,63097.0,4705.0,4705.0,5.923883e+04,1.263000e+03,1.486333e+03,835.833,4698.667,279.333,6.780200e+04
"Abilene, TX Metro Area",176579.0,41566.0,135013.0,127862.0,7151.0,7151.0,1.136564e+05,1.420710e+04,3.541517e+03,1135.533,2205.100,267.317,1.350130e+05
"Ada, OK Micro Area",38065.0,2208.0,35857.0,30889.0,4968.0,4968.0,2.493725e+04,1.305250e+03,4.610000e+02,209.583,8920.000,23.917,3.585700e+04
"Adrian, MI Micro Area",99423.0,8494.0,90929.0,86688.0,4241.0,4241.0,8.519940e+04,2.972917e+03,6.934830e+02,738.150,1304.233,20.817,9.092900e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",181208.0,55088.0,126120.0,114935.0,11185.0,11185.0,8.817368e+04,5.683183e+03,2.503308e+04,1984.033,4295.500,950.517,1.261200e+05
"Yuma, AZ Metro Area",203881.0,130003.0,73878.0,69653.0,4225.0,4225.0,6.305157e+04,3.910983e+03,2.772483e+03,1193.350,2610.167,339.450,7.387800e+04
"Zanesville, OH Micro Area",86410.0,1055.0,85355.0,80840.0,4515.0,4515.0,7.908095e+04,4.102117e+03,4.884500e+02,691.333,965.950,26.200,8.535500e+04
"Zapata, TX Micro Area",13889.0,12999.0,890.0,844.0,46.0,46.0,8.147500e+02,1.291700e+01,2.075000e+01,22.500,16.167,2.917,8.900010e+02
United States,331449281.0,62080044.0,269369237.0,255820254.0,13548983.0,13548983.0,1.976426e+08,4.200437e+07,2.129728e+07,3109051.950,4383072.000,932897.383,2.693692e+08

Make note that 'White alone' also include White in combination

In [87]:
#percent_df

final calc: df of percentages

In [88]:
indices = completed_df.index
completed_percent_df = completed_df.copy()
for column in completed_df:
    column_series = completed_df[column]
    completed_percent_df[column] = (column_series/completed_df['Total:']) * 100

In [89]:
completed_percent_df

,Total:,Hispanic or Latino,Not Hispanic or Latino:,Population of one race:,Population of two or more races:,FRACTotal,White Alone and in Combination,Black Alone and in Combination,Asian Alone and in Combination,Other Alone and in Combination,Native Alone and in Combination,NHPI Alone and in Combination,Calc Total (Not Latino)
"Aberdeen, SD Micro Area",100.0,4.067444,95.932556,92.827583,3.104973,3.104973,87.759635,1.616927,2.409329,0.458574,3.568276,0.119817,95.932558
"Aberdeen, WA Micro Area",100.0,10.357502,89.642498,83.421915,6.220583,6.220583,78.320949,1.669840,1.965113,1.105073,6.212210,0.369312,89.642497
"Abilene, TX Metro Area",100.0,23.539606,76.460394,72.410649,4.049745,4.049745,64.365770,8.045747,2.005628,0.643074,1.248789,0.151387,76.460394
"Ada, OK Micro Area",100.0,5.800604,94.199396,81.148036,13.051360,13.051360,65.512282,3.429003,1.211086,0.550592,23.433600,0.062832,94.199396
"Adrian, MI Micro Area",100.0,8.543295,91.456705,87.191093,4.265613,4.265613,85.693854,2.990170,0.697508,0.742434,1.311802,0.020938,91.456705
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yuba City, CA Metro Area",100.0,30.400424,69.599576,63.427111,6.172465,6.172465,48.658825,3.136276,13.814557,1.094893,2.370480,0.524545,69.599576
"Yuma, AZ Metro Area",100.0,63.764157,36.235843,34.163556,2.072287,2.072287,30.925671,1.918268,1.359854,0.585317,1.280240,0.166494,36.235843
"Zanesville, OH Micro Area",100.0,1.220924,98.779076,93.553987,5.225090,5.225090,91.518285,4.747271,0.565270,0.800061,1.117868,0.030321,98.779076
"Zapata, TX Micro Area",100.0,93.592051,6.407949,6.076751,0.331197,0.331197,5.866153,0.093002,0.149399,0.161999,0.116401,0.021002,6.407956
United States,100.0,18.729877,81.270123,77.182323,4.087800,4.087800,59.629808,12.672940,6.425501,0.938017,1.322396,0.281460,81.270123

In [90]:
completed_df.to_csv(f'calculated_metro-micro_Census.csv')

In [91]:
completed_percent_df.to_csv(f'percent-calculated_metro-micro_Census.csv')